org: paddyredbeard
app: what-ip
service: what-ip
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2

functions:
  json:
    handler: handler.json
    events:
      - httpApi:
          path: /ip.json
          method: get
  plaintext:
    handler: handler.plain
    events:
      - httpApi:
          path: /ip
          method: get

plugins:
  - serverless-offline
